In [ ]:
from wind_tools import *
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [ ]:
def rotate(tens, ang, axes):
    rot_matrix = torch.tensor([[np.cos(ang), -np.sin(ang)],
                       [np.sin(ang), np.cos(ang)]])
#     tens[:, axes] = tens[:, axes].matmul(rot_matrix)

    return tens[:, axes].matmul(rot_matrix)

In [ ]:
a = torch.rand(10,3)

In [ ]:
a

tensor([[0.2504, 0.7651, 0.7969],
        [0.9249, 0.8154, 0.5175],
        [0.5828, 0.6478, 0.1577],
        [0.7255, 0.8668, 0.5119],
        [0.5486, 0.3137, 0.9872],
        [0.9501, 0.2956, 0.9394],
        [0.1320, 0.4460, 0.2214],
        [0.0407, 0.0087, 0.8988],
        [0.9168, 0.6311, 0.8477],
        [0.7595, 0.2317, 0.2994]])

In [ ]:
rotate(a, np.pi/2, (1,0))

tensor([[ 0.2504, -0.7651],
        [ 0.9249, -0.8154],
        [ 0.5828, -0.6478],
        [ 0.7255, -0.8668],
        [ 0.5486, -0.3137],
        [ 0.9501, -0.2956],
        [ 0.1320, -0.4460],
        [ 0.0407, -0.0087],
        [ 0.9168, -0.6311],
        [ 0.7595, -0.2317]])

tensor([[8.7619e-01, 4.1187e-01],
        [3.8698e-01, 2.0479e-01],
        [4.7621e-01, 1.0124e-02],
        [3.1815e-01, 5.3165e-01],
        [1.3482e-01, 7.5777e-02],
        [1.8269e-02, 2.8209e-01],
        [4.0369e-02, 6.5251e-01],
        [3.1326e-01, 5.7957e-01],
        [5.8574e-01, 9.2169e-02],
        [3.3792e-01, 8.5321e-02],
        [5.7747e-01, 9.2751e-01],
        [9.6824e-01, 9.8560e-01],
        [2.4148e-01, 1.2062e-01],
        [7.2830e-01, 5.8466e-01],
        [4.0285e-01, 4.4225e-01],
        [2.3305e-02, 5.9641e-01],
        [8.5295e-01, 9.1470e-01],
        [8.0659e-01, 2.6784e-01],
        [3.2949e-01, 9.6715e-02],
        [5.2099e-01, 2.8838e-01],
        [7.1896e-01, 6.9422e-01],
        [6.3682e-01, 7.1999e-01],
        [9.7304e-01, 1.1966e-01],
        [9.8793e-01, 9.0358e-01],
        [8.4783e-01, 2.0927e-01],
        [4.8787e-01, 9.7272e-01],
        [8.0711e-02, 6.6972e-02],
        [5.8296e-01, 7.0184e-01],
        [6.6751e-01, 1.3595e-01],
        [4.990